### ISSUE TITLE
Examples of async validations

### ISSUE THREAD

**Issue by CodeOfficer** [zestia/ember-validation#5]
Zestia, thank you for your work!

I'm digging through the code and trying to write an async constraint ... like to verify uniqueness on an email field ... do you have any examples of how this is supposed to work? It seems like at the core of your project you consider async validations so I'm expecting this to work.

**Comment by amk221** [comment]
Ah I see...

Because the addon resolves the objects and its values before running the constraints, it didn't seem neccessary to support async contraints.

But perhaps you have a usecase the addon has not considered?

Can you elaborate, and we could wiggle in support for that.

**Comment by bagby** [comment]
We need to make a server call to check for email uniqueness when creating a new user.

I created a PR for it #7

**Comment by amk221** [comment]
Ah ok, so you did :)
I did a branch, basically the same as yours. I've added a [test too](https://github.com/zestia/ember-validation/compare/async-constraints#diff-b9553b4dbb1ab426582d632105b2886561698fd77293e2243f5068b3961c9448R183)

**Comment by amk221** [comment]
Uncanny :D

**Comment by amk221** [comment]
Released as 4.2.0
